import { BuildingDesignSchema, type BuildingDesign } from "./schema.js";
export type LandmarkTemplate = "pentagon_complex" | "bundled_tube_skyscraper" | "castle" | "cathedral" | "mansion" | "greenhouse" | "bridge" | "museum";
const base = (name: string, description: string, scale: BuildingDesign["scale"], components: BuildingDesign["components"], colorful = false): BuildingDesign => BuildingDesignSchema.parse({ name, description, anchor: "owner", orientation: "north", scale, palette: { foundation: "cobblestone", primary: "stone_bricks", secondary: "smooth_stone", frame: "dark_oak_planks", glass: "glass", roof: "stone_bricks", floor: "oak_planks", accent: colorful ? "cyan_concrete" : "red_carpet", lighting: "torch", furniture: "bookshelf" }, components, decoration: { interior: true, colorful, lighting: true } });
export function landmarkTemplate(template: LandmarkTemplate, scale: BuildingDesign["scale"] = "medium"): BuildingDesign {
  if (template === "pentagon_complex") { const r = scale === "small" ? 12 : scale === "large" ? 28 : 18; return base("Pentagon", "Scaled low-rise five-sided complex with courtyard and radial corridors", scale, [{ type: "polygon_prism", sides: 5, radius: r, height: 5, mode: "ring" }, { type: "polygon_prism", sides: 5, radius: Math.max(5, r - 5), height: 4, mode: "ring" }, { type: "wall", start: { x: 0, y: 0, z: 0 }, end: { x: r - 5, y: 0, z: 0 }, height: 3, thickness: 2 }, { type: "wall", start: { x: 0, y: 0, z: 0 }, end: { x: 0, y: 0, z: r - 5 }, height: 3, thickness: 2 }, { type: "decoration", kind: "lighting", count: 12 }, { type: "decoration", kind: "accent", count: 10 }, { type: "window_pattern", rows: 2, columns: 12, spacing: 2, margins: 2 }]); }
  if (template === "bundled_tube_skyscraper") { const h = scale === "small" ? 24 : scale === "large" ? 56 : 40; return base("Willis Tower-inspired skyscraper", "Nine-square bundled-tube interpretation with setbacks, lobby, floors, windows and antenna", scale, [{ type: "bundled_towers", layout: "grid", heights: [h, h, h, h, h - 8, h - 8, h - 16, h - 16, h - 16], width: 8, depth: 8 }, { type: "floor", width: 24, depth: 24, y: 1 }, { type: "floor", width: 16, depth: 16, y: Math.floor(h / 2) }, { type: "roof", width: 24, depth: 24, height: 2, style: "spire", transform: { offset: { x: 0, y: h - 1, z: 0 } } }, { type: "window_pattern", rows: 12, columns: 12, spacing: 2, margins: 1 }, { type: "interior_zone", kind: "lobby", width: 20, depth: 20, height: 4 }, { type: "decoration", kind: "lighting", count: 48 }, { type: "decoration", kind: "furniture", count: 24 }]); }
  if (template === "castle") return base("Castle", "Fortified courtyard castle with four corner towers", scale, [{ type: "cuboid", width: 28, depth: 28, height: 7, mode: "hollow" }, { type: "tower", footprint: { shape: "rectangular", width: 7, depth: 7 }, height: 12 }, { type: "tower", footprint: { shape: "rectangular", width: 7, depth: 7 }, height: 12, transform: { offset: { x: 21, y: 0, z: 0 } } }, { type: "tower", footprint: { shape: "rectangular", width: 7, depth: 7 }, height: 12, transform: { offset: { x: 0, y: 0, z: 21 } } }, { type: "tower", footprint: { shape: "rectangular", width: 7, depth: 7 }, height: 12, transform: { offset: { x: 21, y: 0, z: 21 } } }, { type: "door", width: 2, height: 3 }, { type: "decoration", kind: "lighting", count: 20 }]);
  if (template === "cathedral") return base("Cathedral", "Tall nave with twin towers, arches, stained-glass windows and lighting", scale, [{ type: "cuboid", width: 22, depth: 42, height: 18, mode: "hollow" }, { type: "tower", footprint: { shape: "rectangular", width: 8, depth: 8 }, height: 28, transform: { offset: { x: 0, y: 0, z: 34 } } }, { type: "tower", footprint: { shape: "rectangular", width: 8, depth: 8 }, height: 28, transform: { offset: { x: 14, y: 0, z: 34 } } }, { type: "window_pattern", rows: 6, columns: 8, spacing: 3, margins: 2 }, { type: "decoration", kind: "lighting", count: 24 }]);
  if (template === "museum") return base("Futuristic glass museum", "Glass public museum with colorful interior zones and lobby", scale, [{ type: "cuboid", width: 30, depth: 24, height: 10, mode: "hollow", material: "glass" }, { type: "floor", width: 28, depth: 22, y: 0 }, { type: "interior_zone", kind: "lobby", width: 24, depth: 18, height: 4 }, { type: "decoration", kind: "accent", count: 60 }, { type: "decoration", kind: "lighting", count: 20 }], true);
  if (template === "greenhouse") return base("Greenhouse", "Glass greenhouse with planted interior", scale, [{ type: "cuboid", width: 18, depth: 12, height: 8, mode: "hollow", material: "glass" }, { type: "decoration", kind: "plants", count: 24 }]);
  if (template === "bridge") return base("Bridge", "Bounded stone bridge", scale, [{ type: "wall", start: { x: 0, y: 0, z: 0 }, end: { x: 32, y: 0, z: 0 }, height: 4, thickness: 3 }, { type: "decoration", kind: "lighting", count: 8 }]);
  return base(template === "mansion" ? "Mansion" : "Museum", "Composed public building", scale, [{ type: "cuboid", width: 20, depth: 18, height: 8, mode: "hollow" }, { type: "roof", width: 20, depth: 18, height: 3, style: "peaked" }, { type: "window_pattern", rows: 3, columns: 8, spacing: 2, margins: 1 }, { type: "decoration", kind: "lighting", count: 16 }]);
}
export function recognizeLandmark(text: string): LandmarkTemplate | null { const s = text.toLowerCase(); if (/\b(pentagon|us pentagon|pentagon building)\b/.test(s)) return "pentagon_complex"; if (/sears tower|willis tower|chicago skyscraper/.test(s)) return "bundled_tube_skyscraper"; if (/castle/.test(s)) return "castle"; if (/cathedral/.test(s)) return "cathedral"; if (/museum/.test(s)) return "museum"; if (/greenhouse/.test(s)) return "greenhouse"; if (/bridge/.test(s)) return "bridge"; if (/mansion/.test(s)) return "mansion"; return null; }
